version: '3.8'

services:
  frontend:
    image: bhatia2akshit/frontend-fillmyform:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: bhatia2akshit/backend-fillmyform:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_KEY=${AZURE_KEY}
      - PORT=5000  # For Azure compatibility
      - WEBSITES_PORT=5000  # Azure-specific setting
    networks:
      - app-network

networks:
  app-network:
    driver: bridge